# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ccc0b32414931ec25adeb5d83a643e0c67cfcb8204451e8113bbf55fa0bccfa70dfde6692a9020a023cc85dc1188e01bec181dd327ce80cf5be5c40bd55df00

test:
  secret_key_base: 4913735fbced60e8f43a7297f5a480fa29e03491dfe0ba85b1b7213996ee4f71b85ff08986a8661616930780f82c0ef57a3151e4f6fc385ae28439a39d024210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
